### ISSUE TITLE
Twitterverbindung herstellen

### ISSUE THREAD

**Issue by AlisaNikia** [gebruederheitz/Black-Forest-Medical#2]
**Kundenkommentar:**

> Könntet ihr hier bitte den Link zu @BFMedicalGroup herstellen? Durch die Namensänderung bei Twitter hat es diesen gekappt.
> (https://twitter.com/BFMedicalGroup)

**Comment by steffi501** [comment]
Ist gefixt. Betrifft nur den Link im Footer - oder?

**Comment by AlisaNikia** [comment]
ja, genau :)

**Comment by AlisaNikia** [comment]
Danke Steffi.
